-- ------------------------------------------------------------
-- Schema MySQL pentru hypermarket_activities
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS HYPERMARKET_ACTIVITIES
  CHARACTER SET UTF8MB4
  COLLATE UTF8MB4_UNICODE_CI;

USE HYPERMARKET_ACTIVITIES;

-- (opțional) pentru a reimporta curat
-- SET FOREIGN_KEY_CHECKS = 0;
-- DROP TABLE IF EXISTS ClientiCupoane, ReduceriTemporare, DetaliiComenzi, ComenziFurnizori, Furnizori,
--   Retururi, Plati, MetodePlata, DetaliiPromotii, Promotii, Inventar, DetaliiBon, Bon, Produs,
--   CategoriiProduse, NotificariAdmin, NotificariAngajat, NotificariClient, Schimb, CarduriLoialitate,
--   Cupoane, Admin, Angajat, Client;
-- SET FOREIGN_KEY_CHECKS = 1;

-- 1) Tabele „de bază” fără dependențe
CREATE TABLE CLIENT (
    ID_CLIENT INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    TELEFON VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE ANGAJAT (
    ID_ANGAJAT INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    DATA_ANGAJARE DATE NOT NULL,
    POZITIE VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE ADMIN (
    ID_ADMIN INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    DATA_ANGAJARE DATE NOT NULL,
    NIVEL_ACCESS VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE CATEGORIIPRODUSE (
    ID_CATEGORIE INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE METODEPLATA (
    ID_METODA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIERE VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE FURNIZORI (
    ID_FURNIZOR INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL UNIQUE,
    ADRESA VARCHAR(100) NOT NULL,
    TELEFON VARCHAR(20) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE PROMOTII (
    ID_PROMOTIE INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIERE TEXT NOT NULL,
    DATA_INCEPUT DATETIME NOT NULL,
    DATA_SFARSIT DATETIME NOT NULL
) ENGINE=INNODB;

CREATE TABLE CUPOANE (
    ID_CUPON INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIERE TEXT NOT NULL,
    DATA_INCEPUT DATETIME NOT NULL,
    DATA_SFARSIT DATETIME NOT NULL,
    VAL_REDUCERE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CHK_CUPON_VAL CHECK (VAL_REDUCERE >= 0 AND VAL_REDUCERE <= 100)
) ENGINE=INNODB;

-- 2) Tabele dependente de produse/categorii
CREATE TABLE PRODUS (
    ID_PRODUS INT PRIMARY KEY AUTO_INCREMENT,
    NUME VARCHAR(50) NOT NULL,
    PRET DECIMAL(10, 2) NOT NULL,
    ID_CATEGORIE INT NOT NULL,
    CONSTRAINT CHK_PRODUS_PRET CHECK (PRET >= 0),
    CONSTRAINT FK_PRODUS_CATEGORIE FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIIPRODUSE(ID_CATEGORIE)
) ENGINE=INNODB;

CREATE TABLE INVENTAR (
    ID_INVENTAR INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL,
    DATA_ACTUALIZARE DATETIME NOT NULL,
    CONSTRAINT CHK_INVENTAR_CANT CHECK (CANTITATE >= 0),
    CONSTRAINT FK_INVENTAR_PRODUS FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
) ENGINE=INNODB;

CREATE TABLE REDUCERITEMPORARE (
    ID_DISCOUNT INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUS INT NOT NULL,
    DATA_INCEPUT DATETIME NOT NULL,
    DATA_SFARSIT DATETIME NOT NULL,
    REDUCERE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CHK_REDUCERE_TEMP CHECK (REDUCERE >= 0 AND REDUCERE <= 1),
    CONSTRAINT FK_REDUCERE_TEMP_PRODUS FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
) ENGINE=INNODB;

CREATE TABLE DETALIIPROMOTII (
    ID_DETALIU INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROMOTIE INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    REDUCERE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CHK_DETALII_PROMOTII_REDUC CHECK (REDUCERE >= 0 AND REDUCERE <= 1),
    CONSTRAINT FK_DETALII_PROMOTII_PROM FOREIGN KEY (ID_PROMOTIE) REFERENCES PROMOTII(ID_PROMOTIE),
    CONSTRAINT FK_DETALII_PROMOTII_PROD FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
) ENGINE=INNODB;

-- 3) Bonuri și plăți
CREATE TABLE BON (
    ID_BON INT PRIMARY KEY AUTO_INCREMENT,
    DATA_BON DATE NOT NULL,
    ID_CLIENT INT NOT NULL,
    ID_ANGAJAT INT NOT NULL,
    CONSTRAINT FK_BON_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT FK_BON_ANGAJAT FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
) ENGINE=INNODB;

CREATE TABLE DETALIIBON (
    ID_DETALIUBON INT PRIMARY KEY AUTO_INCREMENT,
    ID_BON INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL,
    PRET_VANZARE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CHK_DETALII_BON_CANT CHECK (CANTITATE > 0),
    CONSTRAINT CHK_DETALII_BON_PRET CHECK (PRET_VANZARE >= 0),
    CONSTRAINT FK_DETALII_BON_BON FOREIGN KEY (ID_BON) REFERENCES BON(ID_BON),
    CONSTRAINT FK_DETALII_BON_PROD FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
) ENGINE=INNODB;

CREATE TABLE PLATI (
    ID_PLATA INT PRIMARY KEY AUTO_INCREMENT,
    ID_BON INT NOT NULL,
    ID_METODA INT NOT NULL,
    SUMA DECIMAL(10, 2) NOT NULL,
    `DATA` DATETIME NOT NULL,
    CONSTRAINT CHK_PLATI_SUMA CHECK (SUMA >= 0),
    CONSTRAINT FK_PLATI_BON FOREIGN KEY (ID_BON) REFERENCES BON(ID_BON),
    CONSTRAINT FK_PLATI_METODA FOREIGN KEY (ID_METODA) REFERENCES METODEPLATA(ID_METODA)
) ENGINE=INNODB;

CREATE TABLE RETURURI (
    ID_RETUR INT PRIMARY KEY AUTO_INCREMENT,
    ID_DETALIU INT NOT NULL,
    MOTIV TEXT NOT NULL,
    `DATA` DATE NOT NULL,
    CONSTRAINT FK_RETUR_DETALIU FOREIGN KEY (ID_DETALIU) REFERENCES DETALIIBON(ID_DETALIUBON)
) ENGINE=INNODB;

-- 4) Furnizori și comenzi
CREATE TABLE COMENZIFURNIZORI (
    ID_COMANDA INT PRIMARY KEY AUTO_INCREMENT,
    ID_FURNIZOR INT NOT NULL,
    DATA_COMANDA DATETIME NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT FK_COMANDA_FURNIZOR FOREIGN KEY (ID_FURNIZOR) REFERENCES FURNIZORI(ID_FURNIZOR)
) ENGINE=INNODB;

CREATE TABLE DETALIICOMENZI (
    ID_DETALIU INT PRIMARY KEY AUTO_INCREMENT,
    ID_COMANDA INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL,
    PRET DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CHK_DETALII_COMENZI_CANT CHECK (CANTITATE > 0),
    CONSTRAINT CHK_DETALII_COMENZI_PRET CHECK (PRET >= 0),
    CONSTRAINT FK_DETALII_COMENZI_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMENZIFURNIZORI(ID_COMANDA),
    CONSTRAINT FK_DETALII_COMENZI_PROD FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
) ENGINE=INNODB;

-- 5) Loialitate + cupoane
CREATE TABLE CARDURILOIALITATE (
    ID_CARD INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENT INT NOT NULL,
    NUMAR_CARD VARCHAR(50) NOT NULL UNIQUE,
    PUNCTE INT NOT NULL,
    CONSTRAINT CHK_CARD_PUNCTE CHECK (PUNCTE >= 0),
    CONSTRAINT FK_CARD_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
) ENGINE=INNODB;

CREATE TABLE CLIENTICUPOANE (
    ID_CLIENT INT NOT NULL,
    ID_CUPON INT NOT NULL,
    DATA_ATRIBUIRE DATETIME NOT NULL,
    DATA_UTILIZARE DATETIME NULL,
    PRIMARY KEY (ID_CLIENT, ID_CUPON),
    CONSTRAINT FK_CLIENTICUPOANE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT FK_CLIENTICUPOANE_CUPON FOREIGN KEY (ID_CUPON) REFERENCES CUPOANE(ID_CUPON)
) ENGINE=INNODB;

-- 6) Schimburi
CREATE TABLE SCHIMB (
    ID_SCHIMB INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANGAJAT INT NOT NULL,
    DATA_START DATETIME NOT NULL,
    DATA_END DATETIME NOT NULL,
    CONSTRAINT FK_SCHIMB_ANGAJAT FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
) ENGINE=INNODB;

-- 7) Notificări (separate)
CREATE TABLE NOTIFICARICLIENT (
    ID_NOTIFICARE INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENT INT NOT NULL,
    MESAJ TEXT NOT NULL,
    `DATA` DATETIME NOT NULL,
    CONSTRAINT FK_NOTIF_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
) ENGINE=INNODB;

CREATE TABLE NOTIFICARIANGAJAT (
    ID_NOTIFICARE INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANGAJAT INT NOT NULL,
    MESAJ TEXT NOT NULL,
    `DATA` DATETIME NOT NULL,
    CONSTRAINT FK_NOTIF_ANGAJAT FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
) ENGINE=INNODB;

CREATE TABLE NOTIFICARIADMIN (
    ID_NOTIFICARE INT PRIMARY KEY AUTO_INCREMENT,
    ID_ADMIN INT NOT NULL,
    MESAJ TEXT NOT NULL,
    `DATA` DATETIME NOT NULL,
    CONSTRAINT FK_NOTIF_ADMIN FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN)
) ENGINE=INNODB;

-- ------------------------------------------------------------
-- Sfârșit schema
-- ------------------------------------------------------------